version: '2'
services:
  minecraft:
    image: itzg/minecraft-server
    environment:
      - EULA=TRUE
      - VERSION=1.17.1
    ports:
      - "25565:25565"
    volumes:
      - ./dir/data:/data
    restart: always
  nginx:
    image: nginx
    volumes:
      - ./dir/web:/usr/share/nginx/html
    ports:
      - "80:80"
    restart: always
  overviewer:
    image: mide/minecraft-overviewer:latest
    environment:
      - MINECRAFT_VERSION=1.17.1
    volumes:
      - ./dir/data:/home/minecraft/server:ro
      - ./dir/web:/home/minecraft/render:rw
    restart: always
